### ISSUE TITLE
web report view doesn't present "Testsuite was run only with 'harness'"

### ISSUE THREAD

**Issue by tonycoz** [abeltje/Perl5-CoreSmokeDB-Web#1]
Compare:

https://www.nntp.perl.org/group/perl.daily-build.reports/2023/05/msg293631.html

and

https://perl5.test-smoke.org/report/5034350

These appears to be different presentations of the same report, but the second isn't showing the "Testsuite was run only with 'harness'" message.

Looking at the data for 5034350 "harness_only" is set to the string `"1"` rather than the number 1 which might be\* why the JS in `src/components/P5SDBFullReport.vue` isn't displaying the message:
```
<span v-if="rd.harness_only === 1">
Testsuite was run only with 'harness'</span>
```
\* not that I know anything about vue

**Comment by abeltje** [comment]
```diff
--- a/src/components/P5SDBFullReport.vue
+++ b/src/components/P5SDBFullReport.vue
@@ -32,7 +32,7 @@ c = Configure, m = make, M = make (after miniperl), t = make test-prep
 ----------------------- ----------------------------------------------------
 {{ rd.matrix }}
 
-<span v-if="rd.harness_only === 1">
+<span v-if="rd.harness_only == 1">
 Testsuite was run only with 'harness'</span>
 <span v-if="hasLength(rd.applied_patches)">
 Applied patches:
```
